version: '3.8'

services:
  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=to-do-list
      - JWT_SECRET=nestBackendJelou
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MONGODB_URI=
    depends_on:
      - db
      - redis
      - mongodb
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: to-do-list
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql

  redis:
    image: redis:6-alpine
    ports:
      - '6379:6379'

  mongodb:
    image: mongo:5.0
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

volumes:
  db_data:
  mongo_data:
